### ISSUE TITLE
Milestone 1 feedback

### ISSUE THREAD

**Issue by eric-f** [UBC-MDS/DSCI_522_Forest_Fire_Analysis#17]
__Mechanics__
- [ ] Might want to add version number for the packages in the dependency section.
- [ ] Might want to add a link to the final report in README.

__Quality__
- [ ] In the documentation at the top of an R script, you can explain what the arguments are in addition to showing an usage example.

__Report__
- [ ] Since you are showing Table 1, would be nice to list the definitions of the variables. Say, what is FFMC DMC, DC and ISI?
- [ ] The figures are not showing up in `Report.md`
- [ ] In Table 3, what is `lower` and `upper`?
